# Generated by Django 5.0.2 on 2024-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('user', 'payment_date'), 'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date_of_payment',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='session',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='сумма оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'наличные'), ('transfer', 'перевод')], max_length=20, verbose_name='способ оплаты'),
        ),
    ]
