# Generated by Django 5.0.2 on 2024-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_rename_user_coursesubscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена курса'),
        ),
    ]
